[versions]
android-tools = "32.2.1"
agp = "9.2.1"
kotlin = "2.3.0"
paparazzi = "2.0.0-alpha04"
javalin = "6.3.0"
slf4j = "2.0.16"

[libraries]
com-android-tools-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-tools" }
com-android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }
com-android-tools-annotations = { module = "com.android.tools:annotations", version.ref = "android-tools" }
junit = "junit:junit:4.13.2"
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
